; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=bpf -mcpu=v1 | FileCheck %s

%struct.key_t = type { i32, [16 x i8] }

; Function Attrs: nounwind uwtable
define i32 @test() #0 {
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    r6 = 0
; CHECK-NEXT:    *(u32 *)(r10 - 8) = r6
; CHECK-NEXT:    *(u64 *)(r10 - 16) = r6
; CHECK-NEXT:    *(u64 *)(r10 - 24) = r6
; CHECK-NEXT:    r1 = r10
; CHECK-NEXT:    r1 += -20
; CHECK-NEXT:    call test1
; CHECK-NEXT:    r0 = r6
; CHECK-NEXT:    exit
  %key = alloca %struct.key_t, align 4
  call void @llvm.memset.p0.i64(ptr align 4 %key, i8 0, i64 20, i1 false)
  %1 = getelementptr inbounds %struct.key_t, ptr %key, i64 0, i32 1, i64 0
  call void @test1(ptr %1) #3
  ret i32 0
}

; Function Attrs: nounwind argmemonly
declare void @llvm.memset.p0.i64(ptr nocapture, i8, i64, i1) #1

declare void @test1(ptr) #2
