; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=bpfel -mattr=+alu32 -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=bpfeb -mattr=+alu32 -verify-machineinstrs | FileCheck %s

; Test that %w works as input constraint
; CHECK-LABEL: test_inlineasm_w_input_constraint
define dso_local i32 @test_inlineasm_w_input_constraint() {
; CHECK-LABEL: test_inlineasm_w_input_constraint:
; CHECK:       .Ltest_inlineasm_w_input_constraint$local:
; CHECK-NEXT:    .type .Ltest_inlineasm_w_input_constraint$local,@function
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    w0 = 42
; CHECK-NEXT:    #APP
; CHECK-NEXT:    w0 = w0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    exit
  tail call void asm sideeffect "w0 = $0", "w"(i32 42)
  ret i32 42
}

; Test that %w works as output constraint
; CHECK-LABEL: test_inlineasm_w_output_constraint
define dso_local i32 @test_inlineasm_w_output_constraint() {
; CHECK-LABEL: test_inlineasm_w_output_constraint:
; CHECK:       .Ltest_inlineasm_w_output_constraint$local:
; CHECK-NEXT:    .type .Ltest_inlineasm_w_output_constraint$local,@function
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    #APP
; CHECK-NEXT:    w0 = 42
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    exit
  %1 = tail call i32 asm sideeffect "$0 = $1", "=w,i"(i32 42)
  ret i32 %1
}
