; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sme2 -aarch64-new-sme-abi=false < %s | FileCheck %s --check-prefixes=CHECK,OLD-ABI
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sme2 < %s | FileCheck %s --check-prefixes=CHECK,NEW-ABI

define i32 @no_tpidr2_save_required() "aarch64_inout_za" {
; CHECK-LABEL: no_tpidr2_save_required:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w0, #42 // =0x2a
; CHECK-NEXT:    ret
entry:
  ret i32 42
}

define float @multi_bb_stpidr2_save_required(i32 %a, float %b, float %c) "aarch64_inout_za" {
; OLD-ABI-LABEL: multi_bb_stpidr2_save_required:
; OLD-ABI:       // %bb.0:
; OLD-ABI-NEXT:    stp x29, x30, [sp, #-32]! // 16-byte Folded Spill
; OLD-ABI-NEXT:    str x19, [sp, #16] // 8-byte Spill
; OLD-ABI-NEXT:    mov x29, sp
; OLD-ABI-NEXT:    sub sp, sp, #16
; OLD-ABI-NEXT:    .cfi_def_cfa w29, 32
; OLD-ABI-NEXT:    .cfi_offset w19, -16
; OLD-ABI-NEXT:    .cfi_offset w30, -24
; OLD-ABI-NEXT:    .cfi_offset w29, -32
; OLD-ABI-NEXT:    rdsvl x8, #1
; OLD-ABI-NEXT:    mov x9, sp
; OLD-ABI-NEXT:    msub x9, x8, x8, x9
; OLD-ABI-NEXT:    mov sp, x9
; OLD-ABI-NEXT:    stp x9, x8, [x29, #-16]
; OLD-ABI-NEXT:    cbz w0, .LBB1_2
; OLD-ABI-NEXT:  // %bb.1: // %use_b
; OLD-ABI-NEXT:    fmov s1, #4.00000000
; OLD-ABI-NEXT:    fadd s0, s0, s1
; OLD-ABI-NEXT:    b .LBB1_5
; OLD-ABI-NEXT:  .LBB1_2: // %use_c
; OLD-ABI-NEXT:    fmov s0, s1
; OLD-ABI-NEXT:    sub x19, x29, #16
; OLD-ABI-NEXT:    msr TPIDR2_EL0, x19
; OLD-ABI-NEXT:    bl cosf
; OLD-ABI-NEXT:    smstart za
; OLD-ABI-NEXT:    mrs x8, TPIDR2_EL0
; OLD-ABI-NEXT:    mov x0, x19
; OLD-ABI-NEXT:    cbnz x8, .LBB1_4
; OLD-ABI-NEXT:  // %bb.3: // %use_c
; OLD-ABI-NEXT:    bl __arm_tpidr2_restore
; OLD-ABI-NEXT:  .LBB1_4: // %use_c
; OLD-ABI-NEXT:    msr TPIDR2_EL0, xzr
; OLD-ABI-NEXT:  .LBB1_5: // %exit
; OLD-ABI-NEXT:    mov sp, x29
; OLD-ABI-NEXT:    ldr x19, [sp, #16] // 8-byte Reload
; OLD-ABI-NEXT:    ldp x29, x30, [sp], #32 // 16-byte Folded Reload
; OLD-ABI-NEXT:    ret
;
; NEW-ABI-LABEL: multi_bb_stpidr2_save_required:
; NEW-ABI:       // %bb.0:
; NEW-ABI-NEXT:    stp x29, x30, [sp, #-16]! // 16-byte Folded Spill
; NEW-ABI-NEXT:    mov x29, sp
; NEW-ABI-NEXT:    sub sp, sp, #16
; NEW-ABI-NEXT:    .cfi_def_cfa w29, 16
; NEW-ABI-NEXT:    .cfi_offset w30, -8
; NEW-ABI-NEXT:    .cfi_offset w29, -16
; NEW-ABI-NEXT:    rdsvl x8, #1
; NEW-ABI-NEXT:    mov x9, sp
; NEW-ABI-NEXT:    msub x9, x8, x8, x9
; NEW-ABI-NEXT:    mov sp, x9
; NEW-ABI-NEXT:    stp x9, x8, [x29, #-16]
; NEW-ABI-NEXT:    cbz w0, .LBB1_2
; NEW-ABI-NEXT:  // %bb.1: // %use_b
; NEW-ABI-NEXT:    fmov s1, #4.00000000
; NEW-ABI-NEXT:    fadd s0, s0, s1
; NEW-ABI-NEXT:    b .LBB1_5
; NEW-ABI-NEXT:  .LBB1_2: // %use_c
; NEW-ABI-NEXT:    fmov s0, s1
; NEW-ABI-NEXT:    sub x8, x29, #16
; NEW-ABI-NEXT:    msr TPIDR2_EL0, x8
; NEW-ABI-NEXT:    bl cosf
; NEW-ABI-NEXT:    smstart za
; NEW-ABI-NEXT:    mrs x8, TPIDR2_EL0
; NEW-ABI-NEXT:    sub x0, x29, #16
; NEW-ABI-NEXT:    cbnz x8, .LBB1_4
; NEW-ABI-NEXT:  // %bb.3: // %use_c
; NEW-ABI-NEXT:    bl __arm_tpidr2_restore
; NEW-ABI-NEXT:  .LBB1_4: // %use_c
; NEW-ABI-NEXT:    msr TPIDR2_EL0, xzr
; NEW-ABI-NEXT:  .LBB1_5: // %exit
; NEW-ABI-NEXT:    mov sp, x29
; NEW-ABI-NEXT:    ldp x29, x30, [sp], #16 // 16-byte Folded Reload
; NEW-ABI-NEXT:    ret
  %cmp = icmp ne i32 %a, 0
  br i1 %cmp, label %use_b, label %use_c

use_b:
  %faddr = fadd float %b, 4.0
  br label %exit

use_c:
  %res2 = call float @llvm.cos.f32(float %c)
  br label %exit

exit:
  %ret = phi float [%faddr, %use_b], [%res2, %use_c]
  ret float %ret
}

define float @multi_bb_stpidr2_save_required_stackprobe(i32 %a, float %b, float %c) "aarch64_inout_za" "probe-stack"="inline-asm" "stack-probe-size"="65536" {
; OLD-ABI-LABEL: multi_bb_stpidr2_save_required_stackprobe:
; OLD-ABI:       // %bb.0:
; OLD-ABI-NEXT:    stp x29, x30, [sp, #-32]! // 16-byte Folded Spill
; OLD-ABI-NEXT:    str x19, [sp, #16] // 8-byte Spill
; OLD-ABI-NEXT:    mov x29, sp
; OLD-ABI-NEXT:    ldr xzr, [sp, #-16]!
; OLD-ABI-NEXT:    .cfi_def_cfa w29, 32
; OLD-ABI-NEXT:    .cfi_offset w19, -16
; OLD-ABI-NEXT:    .cfi_offset w30, -24
; OLD-ABI-NEXT:    .cfi_offset w29, -32
; OLD-ABI-NEXT:    rdsvl x8, #1
; OLD-ABI-NEXT:    mov x9, sp
; OLD-ABI-NEXT:    msub x9, x8, x8, x9
; OLD-ABI-NEXT:  .LBB2_1: // =>This Inner Loop Header: Depth=1
; OLD-ABI-NEXT:    sub sp, sp, #16, lsl #12 // =65536
; OLD-ABI-NEXT:    cmp sp, x9
; OLD-ABI-NEXT:    b.le .LBB2_3
; OLD-ABI-NEXT:  // %bb.2: // in Loop: Header=BB2_1 Depth=1
; OLD-ABI-NEXT:    ldr xzr, [sp]
; OLD-ABI-NEXT:    b .LBB2_1
; OLD-ABI-NEXT:  .LBB2_3:
; OLD-ABI-NEXT:    mov sp, x9
; OLD-ABI-NEXT:    ldr xzr, [sp]
; OLD-ABI-NEXT:    stp x9, x8, [x29, #-16]
; OLD-ABI-NEXT:    cbz w0, .LBB2_5
; OLD-ABI-NEXT:  // %bb.4: // %use_b
; OLD-ABI-NEXT:    fmov s1, #4.00000000
; OLD-ABI-NEXT:    fadd s0, s0, s1
; OLD-ABI-NEXT:    b .LBB2_8
; OLD-ABI-NEXT:  .LBB2_5: // %use_c
; OLD-ABI-NEXT:    fmov s0, s1
; OLD-ABI-NEXT:    sub x19, x29, #16
; OLD-ABI-NEXT:    msr TPIDR2_EL0, x19
; OLD-ABI-NEXT:    bl cosf
; OLD-ABI-NEXT:    smstart za
; OLD-ABI-NEXT:    mrs x8, TPIDR2_EL0
; OLD-ABI-NEXT:    mov x0, x19
; OLD-ABI-NEXT:    cbnz x8, .LBB2_7
; OLD-ABI-NEXT:  // %bb.6: // %use_c
; OLD-ABI-NEXT:    bl __arm_tpidr2_restore
; OLD-ABI-NEXT:  .LBB2_7: // %use_c
; OLD-ABI-NEXT:    msr TPIDR2_EL0, xzr
; OLD-ABI-NEXT:  .LBB2_8: // %exit
; OLD-ABI-NEXT:    mov sp, x29
; OLD-ABI-NEXT:    ldr x19, [sp, #16] // 8-byte Reload
; OLD-ABI-NEXT:    ldp x29, x30, [sp], #32 // 16-byte Folded Reload
; OLD-ABI-NEXT:    ret
;
; NEW-ABI-LABEL: multi_bb_stpidr2_save_required_stackprobe:
; NEW-ABI:       // %bb.0:
; NEW-ABI-NEXT:    stp x29, x30, [sp, #-16]! // 16-byte Folded Spill
; NEW-ABI-NEXT:    mov x29, sp
; NEW-ABI-NEXT:    ldr xzr, [sp, #-16]!
; NEW-ABI-NEXT:    .cfi_def_cfa w29, 16
; NEW-ABI-NEXT:    .cfi_offset w30, -8
; NEW-ABI-NEXT:    .cfi_offset w29, -16
; NEW-ABI-NEXT:    rdsvl x8, #1
; NEW-ABI-NEXT:    mov x9, sp
; NEW-ABI-NEXT:    msub x9, x8, x8, x9
; NEW-ABI-NEXT:  .LBB2_1: // =>This Inner Loop Header: Depth=1
; NEW-ABI-NEXT:    sub sp, sp, #16, lsl #12 // =65536
; NEW-ABI-NEXT:    cmp sp, x9
; NEW-ABI-NEXT:    b.le .LBB2_3
; NEW-ABI-NEXT:  // %bb.2: // in Loop: Header=BB2_1 Depth=1
; NEW-ABI-NEXT:    ldr xzr, [sp]
; NEW-ABI-NEXT:    b .LBB2_1
; NEW-ABI-NEXT:  .LBB2_3:
; NEW-ABI-NEXT:    mov sp, x9
; NEW-ABI-NEXT:    ldr xzr, [sp]
; NEW-ABI-NEXT:    stp x9, x8, [x29, #-16]
; NEW-ABI-NEXT:    cbz w0, .LBB2_5
; NEW-ABI-NEXT:  // %bb.4: // %use_b
; NEW-ABI-NEXT:    fmov s1, #4.00000000
; NEW-ABI-NEXT:    fadd s0, s0, s1
; NEW-ABI-NEXT:    b .LBB2_8
; NEW-ABI-NEXT:  .LBB2_5: // %use_c
; NEW-ABI-NEXT:    fmov s0, s1
; NEW-ABI-NEXT:    sub x8, x29, #16
; NEW-ABI-NEXT:    msr TPIDR2_EL0, x8
; NEW-ABI-NEXT:    bl cosf
; NEW-ABI-NEXT:    smstart za
; NEW-ABI-NEXT:    mrs x8, TPIDR2_EL0
; NEW-ABI-NEXT:    sub x0, x29, #16
; NEW-ABI-NEXT:    cbnz x8, .LBB2_7
; NEW-ABI-NEXT:  // %bb.6: // %use_c
; NEW-ABI-NEXT:    bl __arm_tpidr2_restore
; NEW-ABI-NEXT:  .LBB2_7: // %use_c
; NEW-ABI-NEXT:    msr TPIDR2_EL0, xzr
; NEW-ABI-NEXT:  .LBB2_8: // %exit
; NEW-ABI-NEXT:    mov sp, x29
; NEW-ABI-NEXT:    ldp x29, x30, [sp], #16 // 16-byte Folded Reload
; NEW-ABI-NEXT:    ret
  %cmp = icmp ne i32 %a, 0
  br i1 %cmp, label %use_b, label %use_c

use_b:
  %faddr = fadd float %b, 4.0
  br label %exit

use_c:
  %res2 = call float @llvm.cos.f32(float %c)
  br label %exit

exit:
  %ret = phi float [%faddr, %use_b], [%res2, %use_c]
  ret float %ret
}

declare float @llvm.cos.f32(float)
